name: API Automation Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  api-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Run API Automation Test
        run: ./gradlew clean test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-report
          path: build/reports/tests/test/

      - name: Upload JUnit Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-result
          path: build/test-results/test/
